const popupData = {
    1: {
      101: "Area 101: This is the left-bottom area with additional details.",
      102: "Area 102: Right-bottom corner details go here.",
      103: "Area 103: Top-right additional information.",
      104: "Area 104: Some information about this section.",
      105: "Area 105: Another relevant detail.",
      106: "Area 106: Right-top information about the floor.",
      107: "Area 107: Left-top corner with details.",
    },
    2: {
      201: "Area 201: This is the left-bottom area with additional details.",
      202: "Area 202: Right-bottom corner details go here.",
      203: "Area 203: Top-right additional information.",
      204: "Area 204: Some information about this section.",
      205: "Area 205: Another relevant detail.",
      206: "Area 206: Right-top information about the floor.",
      207: "Area 207: Left-top corner with details.",
    },
    3: {
      301: "Area 301: This is the left-bottom area with additional details.",
      302: "Area 302: Right-bottom corner details go here.",
      303: "Area 303: Top-right additional information.",
      304: "Area 304: Some information about this section.",
      305: "Area 305: Another relevant detail.",
      306: "Area 306: Right-top information about the floor.",
      307: "Area 307: Left-top corner with details.",
    },
    4: {
      401: "Area 401: This is the left-bottom area with additional details.",
      402: "Area 402: Right-bottom corner details go here.",
      403: "Area 403: Top-right additional information.",
      404: "Area 404: Some information about this section.",
      405: "Area 405: Another relevant detail.",
      406: "Area 406: Right-top information about the floor.",
      407: "Area 407: Left-top corner with details.",
    },
    5: {
      501: "Area 501: This is the left-bottom area with additional details.",
      502: "Area 502: Right-bottom corner details go here.",
      503: "Area 503: Top-right additional information.",
      504: "Area 504: Some information about this section.",
      505: "Area 505: Another relevant detail.",
      506: "Area 506: Right-top information about the floor.",
      507: "Area 507: Left-top corner with details.",
    },
    6: {
      601: "Area 601: This is the left-bottom area with additional details.",
      602: "Area 602: Right-bottom corner details go here.",
      603: "Area 603: Top-right additional information.",
      604: "Area 604: Some information about this section.",
      605: "Area 605: Another relevant detail.",
      606: "Area 606: Right-top information about the floor.",
      607: "Area 607: Left-top corner with details.",
    },
    7: {
      701: "Area 701: This is the left-bottom area with additional details.",
      702: "Area 702: Right-bottom corner details go here.",
      703: "Area 703: Top-right additional information.",
      704: "Area 704: Some information about this section.",
      705: "Area 705: Another relevant detail.",
      706: "Area 706: Right-top information about the floor.",
      707: "Area 707: Left-top corner with details.",
    },
    8: {
      801: "Area 801: This is the left-bottom area with additional details.",
      802: "Area 802: Right-bottom corner details go here.",
      803: "Area 803: Top-right additional information.",
      804: "Area 804: Some information about this section.",
      805: "Area 805: Another relevant detail.",
      806: "Area 806: Right-top information about the floor.",
      807: "Area 807: Left-top corner with details.",
    },
  };


  export default popupData;